# week10/k8s/frontend.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels: { app: frontend }
spec:
  replicas: 1
  selector:
    matchLabels: { app: frontend }

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  progressDeadlineSeconds: 180
  template:
    metadata:
      labels: { app: frontend }
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: frontend
          image: ${ACR_LOGIN_SERVER}/frontend:${IMAGE_TAG}
          ports:
            - containerPort: 80

          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "nginx -s quit || true; sleep 1"]

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 3
            timeoutSeconds: 1
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          volumeMounts:
            - name: frontend-config
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js
      volumes:
        - name: frontend-config
          configMap:
            name: frontend-config
            items:
              - key: config.js
                path: config.js
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-w10e1
  labels: { app: frontend }
spec:
  selector: { app: frontend }
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
